spring:
  application:
    name: ecom-api-gateway


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ecom-order-service
#              uri: http://localhost:8080
              uri: lb://ecom-order-service
              predicates:
                - Path=/order/**
            - id: ecom-inventory-service
#              uri: http://localhost:8081
              uri: lb://ecom-inventory-service
              predicates:
                - Path=/product/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  registry-with-eureka: true
  fetch-registry: true